#ifndef SHADER_STRUCTS_PUSH_CONSTANTS_BLOOM_CONVOLUTION_H
#define SHADER_STRUCTS_PUSH_CONSTANTS_BLOOM_CONVOLUTION_H

#include "../../fields.h"

struct ConvolutionPC
{
    STRUCT_FIELD(float, scale, 0.f);
};

#endif // SHADER_STRUCTS_PUSH_CONSTANTS_BLOOM_CONVOLUTION_H
