#ifndef SHADER_STRUCTS_PUSH_CONSTANTS_BLOOM_GENERATE_KERNEL_H
#define SHADER_STRUCTS_PUSH_CONSTANTS_BLOOM_GENERATE_KERNEL_H

#include "../../fields.h"

struct GenerateKernelPC
{
    STRUCT_FIELD_GLM(vec2, invRenderResolution, 0.f);
};

#endif // SHADER_STRUCTS_PUSH_CONSTANTS_BLOOM_GENERATE_KERNEL_H
