#pragma shader_stage(compute)

#include "shared/shader_structs/push_constants/texture_readback.h"

layout(push_constant) uniform PushConstants { TextureReadbackPC PC; };

layout(binding = 0) uniform texture2D inTexture;
layout(binding = 1) uniform sampler nearestSampler;
layout(std430, binding = 2) buffer Color { vec4 data; }
outColor;

layout(local_size_x = 1) in;
void main()
{
    outColor.data = texture(sampler2D(inTexture, nearestSampler), PC.uv).rgba;
}
