#ifndef SHADER_STRUCTS_PUSH_CONSTANTS_IBL_PREFILTER_RADIANCE_H
#define SHADER_STRUCTS_PUSH_CONSTANTS_IBL_PREFILTER_RADIANCE_H

#include "../fields.h"

struct PrefilterRadiancePC
{
    STRUCT_FIELD_GLM(uint, mipCount, 0);
};

#endif // SHADER_STRUCTS_PUSH_CONSTANTS_IBL_PREFILTER_RADIANCE_H
