#ifndef SHADER_STRUCTS_PUSH_CONSTANTS_TEXTURE_READBACK_H
#define SHADER_STRUCTS_PUSH_CONSTANTS_TEXTURE_READBACK_H

#include "../fields.h"

struct TextureReadbackPC
{
    STRUCT_FIELD_GLM(vec2, uv, {});
};

#endif // SHADER_STRUCTS_PUSH_CONSTANTS_TEXTURE_READBACK_H
