#ifndef SHADER_STRUCTS_PUSH_CONSTANTS_PARTICLES_RENDER_H
#define SHADER_STRUCTS_PUSH_CONSTANTS_PARTICLES_RENDER_H

#include "../../fields.h"

struct RenderPC
{
    STRUCT_FIELD_GLM(uint, frameIndex, 0);
};

#endif // SHADER_STRUCTS_PUSH_CONSTANTS_PARTICLES_RENDER_H
