pushd "%~dp0.."

cmake -B build^
 -DPROSPER_USE_PCH=1^
 -DPROSPER_SETUP_DEPENDENCIES=1^
 -DPROSPER_ALWAYS_O2_DEPENDENCIES=1^
 -DPROSPER_MSVC_CRT_LEAK_CHECK=0^
 -DPROSPER_ALLOCATOR_DEBUG=0^
 -DLIVEPP_PATH=C:/LivePP

popd
