#ifndef SHADER_STRUCTS_PUSH_CONSTANTS_RESTIR_DI_INITIAL_RESERVOIRS_H
#define SHADER_STRUCTS_PUSH_CONSTANTS_RESTIR_DI_INITIAL_RESERVOIRS_H

#include "../../fields.h"

struct InitialReservoirsPC
{
    STRUCT_FIELD_GLM(uint, frameIndex, 0);
};

#endif // SHADER_STRUCTS_PUSH_CONSTANTS_RESTIR_DI_INITIAL_RESERVOIRS_H
