#ifndef SHADER_STRUCTS_PUSH_CONSTANTS_RESTIR_DI_SPATIAL_REUSE_H
#define SHADER_STRUCTS_PUSH_CONSTANTS_RESTIR_DI_SPATIAL_REUSE_H

#include "../../fields.h"

struct SpatialReusePC
{
    STRUCT_FIELD_GLM(uint, frameIndex, 0);
};

#endif // SHADER_STRUCTS_PUSH_CONSTANTS_RESTIR_DI_SPATIAL_REUSE_H
