name: clang-format

on:
  pull_request:

jobs:
  clang-format:
    name: clang-format

    strategy:
      fail-fast: true

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get clang-format 15
        run: sudo apt update && sudo apt install clang-format-15

      - name: Run clang-format
        run: >
          clang-format-15
          -Werror
          --dry-run
          src/*.cpp
          src/**/*.cpp
          src/*.hpp
          src/**/*.hpp
          res/shader/*.*
          res/shader/**/*.*
